apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail

resources:
  - https://github.com/aws-containers/retail-store-sample-app/releases/latest/download/kubernetes.yaml
  - ingress-hostless.yaml

patches:
  - target:
      kind: Service
      name: ui
    path: patch-ui-clusterip.yaml
